spring:
  application:
    name: multi-service-spring-websocket-activeMQBroker
    # Configuration du broker ActiveMQ Artemis
#    activemq:
#      broker-url: tcp://localhost:61616
#      user: admin
#      password: admin
#      # Désactive l'auto-configuration du pool (facultatif selon les besoins)
#      pool:
#        enabled: false
#
#    # Pour JMS (si tu utilises Spring JMS)
#    jms:
#      pub-sub-domain: false  # false = Queue, true = Topic (pub/sub)
#      listener:
#        concurrency: 3-10    # Threads min-max pour le listener
#
#  # Configuration des logs (optionnelle, mais utile pour voir les événements JMS)
#  logging:
#    level:
#      org.springframework.jms: INFO
#      org.apache.activemq: INFO
#      org.springframework.boot.autoconfigure.jms: INFO


server:
  port: 8181

broker:
  host: localhost
  port: 61616
  username: admin
  password: admin